# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "D-log"
description: > # this means to ignore newlines until "email:"
  생각하는 아키텍쳐

email: ehdls6864@naver.com
#blog logo
logo: "/assets/images/logo.jpg"
float_logo: true # true, false (default)
logo_home: "/assets/images/logo_float.jpg"

# blog cover
cover: "/assets/images/main.gif"

name: 'newdoin'
author: 'newdoin'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "https://newdoin.github.io/" # the base hostname & protocol for your site
baseurl: ""

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	github
    url:	https://github.com/newdoin
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:
